#combine_control_expr = false
#condense_wildcard_suffixes = true
edition = "2018"
fn_args_layout = "Compressed"
#format_strings = true
#indent_style = "Visual"
newline_style = "Unix"
max_width = 80
#reorder_impl_items = true
#group_imports = "StdExternalCrate"
#trailing_comma = "Never"
#trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true
